version: 2

project_name: lazydlp

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/lazydlp/main.go

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - name: lazydlp
    repository:
      owner: ayushsharma74
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/ayushsharma74/lazydlp"
    description: "A TUI for yt-dlp written in Go."
    install: |
      bin.install "lazydlp"

aurs:
  - name: lazydlp-bin
    homepage: "https://github.com/ayushsharma74/lazydlp"
    description: "A TUI for yt-dlp written in Go."
    maintainers:
      - "Ayush Sharma <your@email.com>"
    license: MIT
    # Important: This tells the AUR where to download the binary
    url_template: "https://github.com/ayushsharma74/lazydlp/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    # Important: SSH URL for your AUR package
    git_url: "ssh://aur@aur.archlinux.org/lazydlp-bin.git"
    private_key: "{{ .Env.AUR_SSH_KEY }}"
    depends:
      - yt-dlp
    provides:
      - lazydlp
    conflicts:
      - lazydlp
    package: |-
      install -Dm755 "./lazydlp" "${pkgdir}/usr/bin/lazydlp"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: ayushsharma74
    name: lazydlp
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).